# POST http://localhost:3002/auth/register HTTP/1.1
# content-type: application/json

# {
#   "name": "boofers",
#   "email": "loofs.m.brock@gmail.com",
#   "password": "loomssi"
# }

# POST http://localhost:3002/auth/login HTTP/1.1
# content-type: application/json

# {
#   "email": "loofs.m.brock@gmail.com",
#   "password": "loomssi"
# }

# GET http://localhost:3002 HTTP/1.1
# content-type: application/json
# auth-token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzAzZjkxOTgxNzZkNjMzZTkwZjFmYmEiLCJpYXQiOjE2NjEyMDQ3OTksImV4cCI6MTY2MTIwNDg1OX0vl7nx1PMTeDumtIBYBGdEMga5xrZizib-W75db_0dpY'

GET http://localhost:3002/lifx/state HTTP/1.1
content-type: application/json

{
  "lifxID": "D073D56B232F"
}

